### ISSUE TITLE
Error in pyqtgraph

### ISSUE THREAD

**Issue by bhemmerling** [HaeffnerLab/RealSimpleGrapher#8]
With the new spacetime installation, the points in a graph aren't connected. The reason seems to be an issue in the pyqtgraph library.  Since we just installed the latest versions of Qt, this might be the reason. The part that throws the error is in the functions.py file. There is a note that some future versions of Qt might make a problem:

Create all vertices in path. The method used below creates a binary format so that all
vertices can be read in at once. This binary format may change in future versions of Qt,
so the original (slower) method is left here for emergencies:
        #path.moveTo(x[0], y[0])
        #if connect == 'all':
            #for i in range(1, y.shape[0]):
                #path.lineTo(x[i], y[i])
        #elif connect == 'pairs':
            #for i in range(1, y.shape[0]):
                #if i%2 == 0:
                    #path.lineTo(x[i], y[i])
                #else:
                    #path.moveTo(x[i], y[i])
        #elif isinstance(connect, np.ndarray):
            #for i in range(1, y.shape[0]):
                #if connect[i] == 1:
                    #path.lineTo(x[i], y[i])
                #else:
                    #path.moveTo(x[i], y[i])
        #else:
            #raise Exception('connect argument must be "all", "pairs", or array')

------------------------------------------------------------------------------------------------------------------------

The error we get is the following:

 |==============================>>
2017-08-03 17:59:47-0700 [-]     |  Traceback (most recent call last):
2017-08-03 17:59:47-0700 [-]     |    File "rsg.py", line 83, in <module>
2017-08-03 17:59:47-0700 [-]     |      util.runServer(RealSimpleGrapher())
2017-08-03 17:59:47-0700 [-]     |    File "/home/space-time/.virtualenvs/labrad/local/lib/python2.7/site-packages/labrad/util/__init__.py", line 417, in runServer
2017-08-03 17:59:47-0700 [-]     |      reactor.run()
2017-08-03 17:59:47-0700 [-]     |    File "/home/space-time/LabRAD/RealSimpleGrapher/qt4reactor.py", line 225, in run
2017-08-03 17:59:47-0700 [-]     |      self._blockApp.exec_()
2017-08-03 17:59:47-0700 [-]     |    File "/home/space-time/LabRAD/RealSimpleGrapher/qt4reactor.py", line 117, in exec_
2017-08-03 17:59:47-0700 [-]     |      QEventLoop.exec_(self)
2017-08-03 17:59:47-0700 [-]     |    File "/home/space-time/LabRAD/RealSimpleGrapher/qt4reactor.py", line 241, in reactorInvokePrivate
2017-08-03 17:59:47-0700 [-]     |      self.qApp.processEvents() # could change interval
2017-08-03 17:59:47-0700 [-]     |    File "/home/space-time/.virtualenvs/labrad/local/lib/python2.7/site-packages/pyqtgraph/widgets/GraphicsView.py", line 154, in paintEvent
2017-08-03 17:59:47-0700 [-]     |      return QtGui.QGraphicsView.paintEvent(self, ev)
2017-08-03 17:59:47-0700 [-]     |    File "/home/space-time/.virtualenvs/labrad/local/lib/python2.7/site-packages/pyqtgraph/debug.py", line 93, in w
2017-08-03 17:59:47-0700 [-]     |      printExc('Ignored exception:')
2017-08-03 17:59:47-0700 [-]     |    --- exception caught here ---
2017-08-03 17:59:47-0700 [-]     |    File "/home/space-time/.virtualenvs/labrad/local/lib/python2.7/site-packages/pyqtgraph/debug.py", line 91, in w
2017-08-03 17:59:47-0700 [-]     |      func(*args, **kwds)
2017-08-03 17:59:47-0700 [-]     |    File "/home/space-time/.virtualenvs/labrad/local/lib/python2.7/site-packages/pyqtgraph/graphicsItems/PlotCurveItem.py", line 430, in paint
2017-08-03 17:59:47-0700 [-]     |      path = self.getPath()
2017-08-03 17:59:47-0700 [-]     |    File "/home/space-time/.virtualenvs/labrad/local/lib/python2.7/site-packages/pyqtgraph/graphicsItems/PlotCurveItem.py", line 412, in getPath
2017-08-03 17:59:47-0700 [-]     |      self.path = self.generatePath(*self.getData())
2017-08-03 17:59:47-0700 [-]     |    File "/home/space-time/.virtualenvs/labrad/local/lib/python2.7/site-packages/pyqtgraph/graphicsItems/PlotCurveItem.py", line 401, in generatePath
2017-08-03 17:59:47-0700 [-]     |      path = fn.arrayToQPath(x, y, connect=self.opts['connect'])
2017-08-03 17:59:47-0700 [-]     |    File "/home/space-time/.virtualenvs/labrad/local/lib/python2.7/site-packages/pyqtgraph/functions.py", line 1395, in arrayToQPath
2017-08-03 17:59:47-0700 [-]     |      raise Exception('connect argument must be "all", "pairs", "finite", or array')
2017-08-03 17:59:47-0700 [-]     |  Exception: connect argument must be "all", "pairs", "finite", or array

-------------------------------------------------------------

It can be "fixed" temporarily by setting the connect variable in functions.py to 'all' by doing:

connect = 'all'

in the function arrayToQPath in functions.py

**Comment by aransfor** [comment]
This was an error that was fixed with #13
